### ISSUE TITLE
gpsinit can't seem to set port baud rate correctly on RPi Jessie

### ISSUE THREAD

**Issue by K6TD** [f5eng/mt3339-utils#5]
```
gpsinit -s 115200 -f /etc/gpsinit_nav.conf /dev/gps0
Making sure the unit is in NMEA mode
Making sure the speeds match
The GPS speed and the port speed couldn't be synchronized.
Retrying
Making sure the speeds match
The GPS speed and the port speed couldn't be synchronized.
```

`stty -F /dev/gps0 --all
speed 115200 baud; rows 0; columns 0; line = 0;`

Doesn't result in readable data from port.

`stty -F /dev/gps0 9600` resets tty to 9600, which is what the GPS unit is at.

Seemed to work of wheezy.

**Comment by K6TD** [comment]
Ah, stand-by.  More testing indicates the chip isn't receiving ANY commands.  If true, this would be why the chip didn't change speeds.  Investigating.

**Comment by K6TD** [comment]
Never mind. :-(.  Bad HAT.  I won't reveal how it was damaged.

**Comment by cpaelzer** [comment]
I seem to have a similar/the same issue - could you share how you confirmed that it was broken without revealing "why" it was damaged :-) @K6TD ?

**Comment by K6TD** [comment]
Sure...I replaced the HAT and all worked just fine.  I don't recall how I damaged the HAT, now. That was over a year ago.  I did damage it electrically.  I think I either installed it mis-aligned, or some other mistake like that.
